# xdhqxdh.appveyor

environment:
  version: 20180816
  affix: xdhqxdh

skip_tags: true	

platform:
- x86
- x64

configuration: Release

os :
# - Visual Studio 2013
# - Visual Studio 2015
- Visual Studio 2017


after_build:
- if "%platform%"=="x86" set platform=ia32
- echo | set /p="%affix%-v%version%" >>tmpfile.tmp || true
- echo | set /p="-win32-" >>tmpfile.tmp || true
- echo | set /p="%platform%" >>tmpfile.tmp || true
- set /p addon= <tmpfile.tmp
- echo .%addon%.
- set dir=win32-%platform%
- mkdir %dir%
- copy %affix%.dll %dir%
# It MUST be '.tar.gz' to be retrieved by 'node-pre-gyp' when installed with 'npm' !
- 7z a -ttar -so dummy %dir% | 7z a -si %addon%.tar.gz

artifacts:
- path: '*.tar.gz'

deploy:
  tag: v$(version)
  description: ''
  provider: GitHub
  auth_token:
    secure: kKebvPLjikQbZ7E1Vm8omoYc9K0wOcKxjWsglp3+D4fV9ev/FaWr8ZBI+AseOTis
  draft: false
  prerelease: false
matrix:
  allow_failures:
    - nodejs_version: "5"
