# xdhq.travis

os:
- linux
- osx

dist: trusty

language: node_js

node_js:
- "4"
- "5"
- "6"
- "7"
- "8"

# To disable building on tags. Tags are supposed to begin with 'v' and only containing digits.
branches:
  except:
    - /^v[0-9]/
matrix:
  allow_failures:
    - node_js: "5"
